---
title: "ENVS-193DS_homework-03-DOC"
author: "Megan Zhao"
date: 5/28/26
format: pdf
toc: true
editor: source
messages: false
warning: false
---

# Set Up

Packages

```{r}
#| label: packages

# reading in packages
library(tidyverse)
library(here)
library(janitor)
library(readxl)

```

Data: 

```{r}
#| label: data

# creating object from 'kelp' from data ** come back to change this for hw and midterm lowkey
kelp <- read.csv(here('data', 'temp-kelp.csv'))

```

Aesthetics

```{r}
#| label: aesthetics

theme_set(theme_bw())

```



# Problem 1

## a.

[The appropriate tests to determine the strength of the relationship between temperature and giant kelp frond elongation rate are the Pearson's correlation test and the Spearman rank correlation test. While both tests can be used to determine relationship strength, Pearson's correlation is parametric, assuming continuous and normally distributed variables with independent observations, and explores the linear relationship between variables. On the other hand, the Spearman rank correlation is non-parametric, assuming independent observations, and explores the monotonic relationship between variables.]

## b.

```{r}
#| label: test-1-visualization

# base layer: ggplot
ggplot(
  # starting data frame
  data = kelp,
  # x-axis
  mapping = aes(x = temp_c,
                # y-axis
                y = kelp_elong)
) +
  # first layer: points
  geom_point(
    # coloring points
    color = 'chartreuse4',
    # changing opacity
    alpha = 0.8
    ) +
  # relabelling x-axis, y-axis, and title
  labs(
    # label x-axis
    x = 'Ocean Temperature (°C)',
    # label y-axis
    y = expression(paste('Giant Kelp Frond Elongation Rate (cm day' ^-1,')')),
    # add chart title
    title = 'Fig. 1-1: Correlation between Ocean Temperature and Giant Kelp Frond Growth')

```

## c.

### assumption checking 

```{r}
#| label: assumption-checking

# base layer: ggplot
ggplot(
  # starting data frame
  data = kelp,
  # x-axis
  mapping = aes(x = temp_c,
                # y-axis
                y = kelp_elong)
) +
  # first layer: points
  geom_point(
    # coloring points
    color = 'chartreuse4',
    # changing opacity
    alpha = 0.8
    ) +
  # relabelling x-axis, y-axis, and title
  labs(
    # label x-axis
    x = 'Ocean Temperature (°C)',
    # label y-axis
    y = expression(paste('Giant Kelp Frond Elongation Rate (cm day' ^-1,')')),
    # add chart title
    title = 'Fig. 1-1: Correlation between Ocean Temperature and Giant Kelp Frond Growth')

```

[Because I plan on running a Spearmans rank correlation test, I checked if my data is independent and monotonic. I checked independence by ensuring that proper methodology was being used when collecting data (data collected individually, stated in Problem 1 introduction), and for a monotonic relationship by creating a visualization. After checking my assumptions, I concluded that I have independent observations, and that my data is monotonic -- as ocean temperature increases, giant kelp frond elongation rate decreases.]

### test running

```{r}
#| label: test-running

# correlation test
cor.test(
  # y-variable
  kelp$kelp_elong,
  # x-variable
  kelp$temp_c,
  # use spearman test
  method = 'spearman',
  # use normal p-approximation
  exact = FALSE)

```

## d.

[]

## e.

[]

## f.

```{r}
#| label: test-2-visualization

```

# Problem 2

## a.

```{r}
#| label: plot-1

```

```{r}
#| label: plot-2

```

## b.

[]

# Problem 3

## a.

[An affective visualization for my personal data could take the form of a drawing, showing box plots -- representing mood -- that are being climbed/conquered by a person. For example, if a good mood leads to more work being completed, an affective visualization could show a raised large stack of papers (higher box plot) with sticky tabs sticking out (overlaid data) and a confident/smiling person lifting them above their head. On the inverse, if a bad mood leads to less work being completed, an affective visualization could show strewn papers on the floor (lower box plot) with balled up papers strewn about (overlaid data) and a dejected/tired person sitting down on them. Ideally this visualization would make the viewer understand the feeling of being unproductive/unwell in terms of work completion.]

## b. 

[insert image]

## c.

[insert image]

## d. 

[]

## e.

[insert hyperlink]

# Problem 4

## a. 

[In this paper, the researchers use multiple statistical tests to analyze the effect of landscape differences (size, disturbance, etc.) on shrew population abundance. The statistical tests that the authors are using to address their main research question are linear regression, logsitic regression, ANOVA, Shapiro-Wilk, and the Kruskal-Wallis tests. Attached below is a table created using data from a linear regression test, showing how different landscapes can impact shrew populations***was working on this -- attach image and what implciations]

## b.

[]

## c.

[]

## d.

[]

